### ISSUE TITLE
DummyNET Driver Not Working

### ISSUE THREAD

**Issue by Linuturk** [Linuturk/webpagetest#49]
HEAT testing today has turned up a few issues.
- AutoLogon isn't being attempted because the server isn't rebooted at the end of the run. I've added a `Restart-Computer` command at the end, but haven't been able to test.
- The AutoLogon scheduled task fix doesn't seem to be running. I've corrected several username issues in relation to this, but it hasn't impacted the primary issue.
- The DummyNET driver doesn't seem to install anymore. We'll need to review that section of code.

@hdansou Where are the logs for the HEAT Powershell run stored? I'd like to review them for errors for these cases.

**Comment by hsAyon** [comment]
Make sure you install the 64bit driver... I had this problem. All you have to do is copy everything except 'ipfw.exe' and 'ipfw.sys' from the 32bit folder of ipfw to the 64bit folder. Then uninstall the previous driver for networks and install the new one. Hope it helped :)

**Comment by docwho76** [comment]
Actually, here is the real fix. The problem stems from the fact that for whatever reason when installing the ipfw driver via mindinst.exe the ipfw.sys driver is not being copied into the System32\Drivers. So to sum up here is how I am able to successfully install the driver now without user intervention:

## The ipfw driver will blow up if your NIC driver has any kind of TCP offloading turned on

Set-NetAdapterAdvancedProperty -Name "Ethernet" -DisplayName "IPv4 Checksum Offload" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "Ethernet" -DisplayName "Large Receive Offload (IPv4)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "Ethernet" -DisplayName "Large Send Offload Version 2 (IPv4)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "Ethernet" -DisplayName "TCP Checksum Offload (IPv4)" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "Ethernet" -DisplayName "UDP Checksum Offload (IPv4)" -DisplayValue "Disabled"

bcdedit /set TESTSIGNING ON  
Restart-Computer

xcopy C:\webpagetest\agent\dummynet\64bit\ipfw.sys C:\Windows\System32\Drivers\ /s /i
.\mindinst.exe c:\webpagetest\dummynet\64bit\netipfw.inf -i -s
Enable-NetAdapterBinding -Name Ethernet -DisplayName ipfw+dummynet

Then if you try the ipfw.cmd script it should work.

**Comment by docwho76** [comment]
You still have to also install the WPOFoundation.cer certificate BTW

Import-Certificate -FilePath C:\installers\WPOFoundation.cer -CertStoreLocation Cert:\LocalMachine\TrustedPublisher

**Comment by Linuturk** [comment]
Thanks for this! I'll give it a shot.

**Comment by Andriy06** [comment]
any luck with this? I did as @triplej7000 suggested to install 64bit driver but still have Cygwin "Couldn't compute FAST_CWD pointer" problem

**Comment by Andriy06** [comment]
actually, now after I install 64bit driver my network stops working completely until I uninstall it

windows 8.1 64bits

**Comment by narendrapavanveyyala** [comment]
1 [main] ipfw 22192 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
my_socket failed 2, cannot talk to kernel module
ipfw: socket: Operation not permitted.
Any suggestions please

**Comment by roshanit1** [comment]
> 1 [main] ipfw 22192 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer. Please report this problem to
> the public mailing list [cygwin@cygwin.com](mailto:cygwin@cygwin.com)
> my_socket failed 2, cannot talk to kernel module
> ipfw: socket: Operation not permitted.
> Any suggestions please

Please provide solution on this
